// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwZRYtiIGB0gVOHyBTgG3iCmICC49iPDU',
    appId: '1:832167208280:web:d2207365906f4c3ab4f12d',
    messagingSenderId: '832167208280',
    projectId: 'my-notes-tabs-apps',
    authDomain: 'my-notes-tabs-apps.firebaseapp.com',
    storageBucket: 'my-notes-tabs-apps.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ_a03O7RqGxiWnED6jFi6rI_VoDES16M',
    appId: '1:832167208280:android:d80018e95cf8420ab4f12d',
    messagingSenderId: '832167208280',
    projectId: 'my-notes-tabs-apps',
    storageBucket: 'my-notes-tabs-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIIw1bc3qJKZQX8yWSM0cZs4cPLryUqqw',
    appId: '1:832167208280:ios:48093e3371c2bfc2b4f12d',
    messagingSenderId: '832167208280',
    projectId: 'my-notes-tabs-apps',
    storageBucket: 'my-notes-tabs-apps.appspot.com',
    iosClientId: '832167208280-0h5km201m7r2qlkqj2uos8f2q91cne9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIIw1bc3qJKZQX8yWSM0cZs4cPLryUqqw',
    appId: '1:832167208280:ios:48093e3371c2bfc2b4f12d',
    messagingSenderId: '832167208280',
    projectId: 'my-notes-tabs-apps',
    storageBucket: 'my-notes-tabs-apps.appspot.com',
    iosClientId: '832167208280-0h5km201m7r2qlkqj2uos8f2q91cne9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
